[package]
name = "stypes"
description = "Shared types"
version = "0.1.0"
edition = "2021"

[features]
rustcore = [
    "tokio"
]

[dependencies]
serde = { workspace = true , features = ["derive"] }
dlt-core = { workspace = true }
bincode = "1.3"
extend = { path = "../tools/extend"}
uuid = { workspace = true, features = ["serde"] }

tokio = { workspace = true , optional = true }

[dev-dependencies]
tokio = { workspace = true  }
