[package]
name = "stypes"
description = "Shared types"
version = "0.1.0"
edition = "2021"

[features]
rustcore = [
    "tokio",
    "walkdir"
]
nodejs = [
    "node-bindgen"
]

[dependencies]
serde = { workspace = true , features = ["derive"] }
dlt-core = { workspace = true }
bincode = "1.3"
extend = { path = "../tools/extend"}
uuid = { workspace = true, features = ["serde"] }

tokio = { workspace = true, optional = true }
node-bindgen = { git = "https://github.com/infinyon/node-bindgen.git", branch="master", optional = true}
thiserror.workspace = true
walkdir = { workspace = true , optional = true}

[dev-dependencies]
tokio = { workspace = true  }
walkdir = { workspace = true }
node-bindgen = { git = "https://github.com/infinyon/node-bindgen.git", branch="master"  }
