[package]
name = "session"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
indexer_base = { path = "../indexer_base" }
processor = { path = "../processor" }
merging = { path = "../merging" }
sources = { path = "../sources" }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.5", features = ["full"] }
tokio-stream = "0.1.5"
tokio-util = "0.6.9"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
notify = "4.0.17"
futures = "0.3"

