[package]
name = "session"
version = "0.1.0"
authors = ["esrlabs.com"]
edition = "2021"

[dependencies]
blake3 = "1.3"
crossbeam-channel.workspace = true
dirs.workspace = true
# dlt-core.workspace = true
# TODO https://github.com/esrlabs/dlt-core/pull/24
dlt-core = { git = "https://github.com/kruss/dlt-core.git", branch = "dlt_network_traces", features=["statistics"] }
envvars = "0.1"
file-tools = { path = "../addons/file-tools" }
futures.workspace = true
indexer_base = { path = "../indexer_base" }
lazy_static.workspace = true
log.workspace = true
merging = { path = "../merging" }
mime_guess = "2.0.4"
parsers = { path = "../parsers" }
processor = { path = "../processor" }
rustc-hash = "1.1"
serde = { workspace = true , features = ["derive"] }
serde_json.workspace = true
serialport = "4.2.2"
sources = { path = "../sources" }
thiserror.workspace = true
tokio = { workspace = true , features = ["full"] }
tokio-stream.workspace = true
tokio-util.workspace = true
uuid = { workspace = true , features = ["serde", "v4"] }
walkdir = "2.3"

[dev-dependencies]
lazy_static.workspace = true
