name: Checks

on: [pull_request]

jobs:
  lint_rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - name: Run clippy on indexer
        working-directory: ./application/apps/indexer
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Run clippy on rustbindings
        working-directory: ./application/apps/rustcore/rs-bindings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install for tests
        working-directory: ./application/apps/rustcore
        run: rake install:all
      - name: Build tests
        working-directory: ./application/apps/rustcore
        run: rake build:all
      - name: Run integration tests
        working-directory: ./application/apps/rustcore
        run: rake test:all
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run unit tests on indexer
        uses: actions-rs/cargo@v1
        working-directory: ./application/apps/indexer
        with:
          command: test
